CREATE DATABASE mobbnb;
\c mobbnb;
CREATE TABLE users(id SERIAL PRIMARY KEY, email VARCHAR(254) NOT NULL, password VARCHAR(254) NOT NULL);
CREATE TABLE spaces(id SERIAL PRIMARY KEY, space_name VARCHAR(100) NOT NULL, space_address VARCHAR(100) NOT NULL);
